"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { formatARS } from "@/lib/currency";

type Customer = { id: string; name: string; emailMasked: string; orderCount: number; totalPurchased: number; lastPurchaseAt: string | null; createdAt: string | null };

export default function CustomersPage() {
  const [customers, setCustomers] = useState<Customer[]>([]); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [query, setQuery] = useState(""); const [error, setError] = useState("");
  useEffect(() => { queueMicrotask(() => { void (async () => { try { const response = await fetch(`/api/admin/customers?page=${page}&q=${encodeURIComponent(query)}`); const data = await response.json() as { customers?: Customer[]; pagination?: { totalPages?: number } }; if (!response.ok) throw new Error(); setCustomers(data.customers ?? []); setPages(data.pagination?.totalPages ?? 1); } catch { setError("No se pudieron cargar los clientes"); } })(); }); }, [page, query]);
  return <main className="ui-admin-main"><div className="mx-auto max-w-7xl"><div className="ui-surface ui-admin-header"><div><h1 className="text-3xl font-semibold">Clientes</h1><p className="mt-2 text-sm text-neutral-600">Datos operativos protegidos para administración.</p></div><Link href="/admin" className="ui-button-secondary">Volver al panel</Link></div><input className="mb-4 w-full rounded-xl border p-3" value={query} onChange={(event) => { setPage(1); setQuery(event.target.value); }} placeholder="Buscar por nombre o email" aria-label="Buscar clientes" />{error ? <p className="mb-4 text-sm text-rose-700">{error}</p> : null}<div className="ui-surface overflow-x-auto"><table className="ui-admin-table"><thead><tr><th>Cliente</th><th>Email</th><th>Órdenes</th><th>Total comprado</th><th>Última compra</th><th>Registro</th></tr></thead><tbody>{customers.map((customer) => <tr key={customer.id}><td>{customer.name}</td><td>{customer.emailMasked}</td><td>{customer.orderCount}</td><td>{formatARS(customer.totalPurchased)}</td><td>{customer.lastPurchaseAt ? new Date(customer.lastPurchaseAt).toLocaleDateString("es-AR") : "Sin información"}</td><td>{customer.createdAt ? new Date(customer.createdAt).toLocaleDateString("es-AR") : "Sin información"}</td></tr>)}</tbody></table>{!customers.length && !error ? <p className="p-4 text-sm text-neutral-600">Sin información</p> : null}</div><div className="mt-4 flex gap-3"><button className="ui-button-secondary" disabled={page === 1} onClick={() => setPage((current) => current - 1)}>Anterior</button><span className="py-2 text-sm">Página {page} de {pages}</span><button className="ui-button-secondary" disabled={page >= pages} onClick={() => setPage((current) => current + 1)}>Siguiente</button></div></div></main>;
}
